# Generated by Django 6.0.1 on 2026-01-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisHistory',
        ),
    ]
