# Generated by Django 6.0.1 on 2026-01-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockCache",
            fields=[
                (
                    "symbol",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, verbose_name="종목코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="종목명")),
                ("market", models.CharField(default="KOSPI", max_length=20, verbose_name="시장")),
                ("sector", models.CharField(blank=True, max_length=100, verbose_name="업종")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="갱신일시")),
            ],
            options={
                "verbose_name": "종목 캐시",
                "verbose_name_plural": "종목 캐시",
                "ordering": ["symbol"],
            },
        ),
    ]
