# Generated by Django 6.0.1 on 2026-01-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "전체 동기화"),
                            ("incremental", "증분 동기화"),
                            ("constituents", "구성종목 업데이트"),
                        ],
                        max_length=20,
                        verbose_name="동기화 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "시작됨"),
                            ("running", "진행중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="started",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="시작 시간")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료 시간"),
                ),
                ("total_stocks", models.IntegerField(default=0, verbose_name="전체 종목 수")),
                ("processed_stocks", models.IntegerField(default=0, verbose_name="처리된 종목 수")),
                ("new_records", models.IntegerField(default=0, verbose_name="신규 레코드 수")),
                ("error_message", models.TextField(blank=True, verbose_name="오류 메시지")),
            ],
            options={
                "verbose_name": "동기화 로그",
                "verbose_name_plural": "동기화 로그",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="stockcache",
            name="is_kospi200",
            field=models.BooleanField(default=False, verbose_name="KOSPI200 여부"),
        ),
        migrations.AddField(
            model_name="stockcache",
            name="last_price_date",
            field=models.DateField(blank=True, null=True, verbose_name="최종 가격 날짜"),
        ),
        migrations.AddField(
            model_name="stockcache",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="마지막 동기화 시간"),
        ),
        migrations.AddField(
            model_name="stockcache",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("syncing", "동기화중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                ],
                default="pending",
                max_length=20,
                verbose_name="동기화 상태",
            ),
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                ("open", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="시가")),
                ("high", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="고가")),
                ("low", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="저가")),
                (
                    "close",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="종가"),
                ),
                ("volume", models.BigIntegerField(verbose_name="거래량")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stockcache",
                        verbose_name="종목",
                    ),
                ),
            ],
            options={
                "verbose_name": "주가 데이터",
                "verbose_name_plural": "주가 데이터",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["stock", "-date"], name="stocks_stoc_stock_i_50f999_idx")
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
