# Generated by Django 6.0.1 on 2026-01-31 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_synclog_stockcache_is_kospi200_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPPLAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_window', models.IntegerField(default=125, verbose_name='최소 윈도우')),
                ('max_window', models.IntegerField(default=750, verbose_name='최대 윈도우')),
                ('step', models.IntegerField(default=5, verbose_name='윈도우 간격')),
                ('analysis_date', models.DateField(verbose_name='분석 기준일')),
                ('confidence_indicator', models.FloatField(verbose_name='LPPLS 신뢰도 지표')),
                ('state', models.CharField(choices=[('CRITICAL', '위험'), ('WARNING', '경고'), ('WATCH', '주의'), ('NORMAL', '정상')], max_length=20, verbose_name='상태')),
                ('message', models.CharField(max_length=200, verbose_name='메시지')),
                ('total_windows', models.IntegerField(verbose_name='전체 윈도우 수')),
                ('successful_fits', models.IntegerField(verbose_name='성공한 피팅 수')),
                ('bubble_windows', models.IntegerField(verbose_name='버블 윈도우 수')),
                ('success_rate', models.FloatField(verbose_name='피팅 성공률')),
                ('computation_time', models.FloatField(blank=True, null=True, verbose_name='계산 시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lppl_results', to='stocks.stockcache', verbose_name='종목')),
            ],
            options={
                'verbose_name': 'LPPL 분석 결과',
                'verbose_name_plural': 'LPPL 분석 결과',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='LPPLWindowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_size', models.IntegerField(verbose_name='윈도우 크기')),
                ('success', models.BooleanField(verbose_name='피팅 성공 여부')),
                ('is_bubble', models.BooleanField(default=False, verbose_name='버블 조건 충족')),
                ('param_tc', models.FloatField(blank=True, null=True, verbose_name='tc (임계시점)')),
                ('param_b', models.FloatField(blank=True, null=True, verbose_name='B (진폭)')),
                ('param_m', models.FloatField(blank=True, null=True, verbose_name='m (지수)')),
                ('param_omega', models.FloatField(blank=True, null=True, verbose_name='omega (각주파수)')),
                ('residual_error', models.FloatField(blank=True, null=True, verbose_name='잔차 오차')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_results', to='stocks.lpplanalysisresult', verbose_name='분석 결과')),
            ],
            options={
                'verbose_name': 'LPPL 윈도우 결과',
                'verbose_name_plural': 'LPPL 윈도우 결과',
                'ordering': ['window_size'],
            },
        ),
        migrations.AddIndex(
            model_name='lpplanalysisresult',
            index=models.Index(fields=['stock', '-analysis_date'], name='stocks_lppl_stock_i_b8f108_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lpplanalysisresult',
            unique_together={('stock', 'analysis_date', 'step')},
        ),
        migrations.AlterUniqueTogether(
            name='lpplwindowresult',
            unique_together={('analysis', 'window_size')},
        ),
    ]
