# Generated by Django 6.0.1 on 2026-01-31 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_lppl_analysis_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentumFactorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(verbose_name='분석 기준일')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='종합 점수')),
                ('signal', models.IntegerField(default=0, verbose_name='매매 신호')),
                ('state', models.CharField(choices=[('VERY_STRONG_BULLISH', '매우 강한 상승'), ('BULLISH', '상승'), ('SLIGHTLY_BULLISH', '약한 상승'), ('NEUTRAL', '중립'), ('SLIGHTLY_BEARISH', '약한 하락'), ('BEARISH', '하락'), ('VERY_STRONG_BEARISH', '매우 강한 하락'), ('INSUFFICIENT_DATA', '데이터 부족')], default='NEUTRAL', max_length=30, verbose_name='모멘텀 상태')),
                ('trend_score', models.FloatField(blank=True, null=True, verbose_name='추세 점수')),
                ('oscillator_score', models.FloatField(blank=True, null=True, verbose_name='오실레이터 점수')),
                ('volume_score', models.FloatField(blank=True, null=True, verbose_name='거래량 점수')),
                ('rsi_score', models.FloatField(blank=True, null=True, verbose_name='RSI 점수')),
                ('macd_score', models.FloatField(blank=True, null=True, verbose_name='MACD 점수')),
                ('adx_score', models.FloatField(blank=True, null=True, verbose_name='ADX 점수')),
                ('roc_score', models.FloatField(blank=True, null=True, verbose_name='ROC 점수')),
                ('stochastic_score', models.FloatField(blank=True, null=True, verbose_name='Stochastic 점수')),
                ('cci_score', models.FloatField(blank=True, null=True, verbose_name='CCI 점수')),
                ('williams_r_score', models.FloatField(blank=True, null=True, verbose_name='Williams %R 점수')),
                ('bb_score', models.FloatField(blank=True, null=True, verbose_name='BB 점수')),
                ('mfi_score', models.FloatField(blank=True, null=True, verbose_name='MFI 점수')),
                ('obv_score', models.FloatField(blank=True, null=True, verbose_name='OBV 점수')),
                ('volume_ma_score', models.FloatField(blank=True, null=True, verbose_name='VolumeMA 점수')),
                ('latest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='최신 종가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentum_scores', to='stocks.stockcache', verbose_name='종목')),
            ],
            options={
                'verbose_name': '모멘텀 팩터 점수',
                'verbose_name_plural': '모멘텀 팩터 점수',
                'ordering': ['-total_score'],
                'indexes': [models.Index(fields=['stock', '-analysis_date'], name='stocks_mome_stock_i_88dd72_idx'), models.Index(fields=['-total_score'], name='stocks_mome_total_s_ff5d22_idx'), models.Index(fields=['state'], name='stocks_mome_state_688f57_idx')],
                'unique_together': {('stock', 'analysis_date')},
            },
        ),
    ]
