# Generated by Django 6.0.1 on 2026-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_momentum_factor_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcache',
            name='is_kosdaq150',
            field=models.BooleanField(default=False, verbose_name='KOSDAQ150 여부'),
        ),
    ]
