# Generated by Django 6.0.1 on 2026-02-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_add_kosdaq150_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='심볼')),
                ('name', models.CharField(max_length=100, verbose_name='지수명')),
                ('category', models.CharField(choices=[('KRX', '한국'), ('US', '미국'), ('GLOBAL', '글로벌')], max_length=10, verbose_name='카테고리')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='시가')),
                ('high', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='고가')),
                ('low', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='저가')),
                ('close', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='종가')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
            ],
            options={
                'verbose_name': '시장 지수',
                'verbose_name_plural': '시장 지수',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='stocks_mark_symbol_89f8ee_idx'), models.Index(fields=['category'], name='stocks_mark_categor_d5ef67_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
